### ISSUE TITLE
[SAAS] Goal tracking added to Google Analytics

### ISSUE THREAD

**Issue by rauhryan** [huboard/huboard-web#179]
Build up analytic goal tracking for HuBoard

- [x] Enterprise Contact/Trial submit
- [x] Enterprise Login to Dashboard
- `shared/analytics` in every view
   - [x] `/login` #194
   - [ ] Errors?
- Login actions
   - [x] `/login/(public|private)` ✓ #232
   - [x] `/login/(public|private)/authorized` ✓ #232
- Basic account actions
   - [x] `/settings/{owner}/trial` when email prompt is shown ✓
   - [x] `/settings/{owner}/trialing` when email prompt is submitted ✓ #207 
   - [x] `/settings/{owner}/expired` when an expired trial board is accessed ✓ #208 
   - [x] `/settings/{owner}/canceled` when a cancelled account board is accessed ✓ #208
- Account reactivation (requirement of https://github.com/huboard/huboard/issues/635)
   - `/settings/{owner}/reactivate` when a long-expired/cancelled board is accessed
   - `/settings/{owner}/reactivating` when a reactivation trial is started
- Board actions
   - [x] `/{owner}/{repo}/board/create` when we offer to create HB labels ✓
   - [x] `/{owner}/{repo}/board/creating` when we are asked to create HB labels ✓ #233
- `/settings/profile` actions
   - [x] `/settings/{owner}/upgrade` when Upgrade is clicked (popping Stripe)
   - [x] `/settings/{owner}/upgrading` when Stripe is successfully submitted (`/settings/charge/dahlbyk`) ✓ #230
   - [x] `/settings/{owner}/canceling` when an account is cancelled ✓ #230
   - What else?

**Comment by dahlbyk** [comment]
Ideas for specific goals:

1. Login Success (New Auth or Returning User)
2. Paywall => Trial Prompt => Trial Signup
3. "Trial Expired" Paywall => Account Upgrade
4. Trial Account (not Expired) => Account Upgrade
5. Enterprise Trial Form => Start Trial

**Comment by rauhryan** [comment]
I must be confusing "Goals" with "segmenting"

I think I get those list items with intercom segmentation

**Comment by dahlbyk** [comment]
Think of a Goal as a funnel - in traditional ecommerce it might be Landing Page :point_right: Product Page :point_right: Cart :point_right: Checkout :point_right: Confirmation.

Traffic segmentation (by source, browser, country, etc) is handled separately, and would be used to filter/compare goal completion, e.g. "Are people who hit HuBoard.com directly more likely to Login than those coming from search engines?" (I would assume so.)

**Comment by rauhryan** [comment]
What's the chain of dependencies?

Goal funnel :point_left: Segmentation

or 

Segmentation :point_left: Goal funnel

**Comment by dahlbyk** [comment]
Think of them as orthogonal.

Segmentation would be classifying use of a board into Guest | Public | Private Trial | Private Paid. If we can push this type of classification into Segment, it can pass it along to GA in a [custom dimension](https://support.google.com/analytics/answer/2709829?hl=en).

A related Goal would be to have someone actually sign up for a trial when presented with the paywall.

**Comment by dahlbyk** [comment]
Alright, here's what I've found so far about the current Analytics implementation:

#### Server

- [`Analytics::Core`](https://github.com/huboard/huboard-web/blob/71594782d4a9a686f10e0938ab977d73d43826eb/lib/analytics/core.rb)
  - [`Saas::Engine`](https://github.com/huboard/huboard-web/blob/71594782d4a9a686f10e0938ab977d73d43826eb/vendor/engines/saas/lib/saas/engine.rb) specifies the [`Segment::Analytics`](https://github.com/segmentio/analytics-ruby) adapter
- [`AnalyticsJob < ActiveJob::Base`](https://github.com/huboard/huboard-web/blob/a95213624edbfb8fcf68bde03719bb603f6ddf04/vendor/engines/saas/app/jobs/analytics_job.rb) encapsulates use of `Analytics::Core`
  - [`GroupOwnerJob < AnalyticsJob`](https://github.com/huboard/huboard-web/blob/a95213624edbfb8fcf68bde03719bb603f6ddf04/vendor/engines/saas/app/jobs/analytics/group_owner_job.rb) fires a `group` event
  - [`IdentifyUserJob < AnalyticsJob`](https://github.com/huboard/huboard-web/blob/a95213624edbfb8fcf68bde03719bb603f6ddf04/vendor/engines/saas/app/jobs/analytics/identify_user_job.rb) fires an `identify` event
  - [`TrackUserJob < AnalyticsJob`](https://github.com/huboard/huboard-web/blob/a95213624edbfb8fcf68bde03719bb603f6ddf04/vendor/engines/saas/app/jobs/analytics/track_user_job.rb) fires a `track` event
- [`BoardIndexJob < ActiveJob::Base`](https://github.com/huboard/huboard-web/blob/1bf5a79a80a47858c7696e810a40c3fbfbfbc5e1/vendor/engines/saas/app/jobs/saas/app/board_index_job.rb) fires a `group` event, using `Analytics::Core` directly
  - I assume this runs conventionally for `board#index`, as the Segment debugger shows frequent Group events via Ruby.
- [`ChargesCreateJob < ActiveJob::Base`](https://github.com/huboard/huboard-web/blob/1bf5a79a80a47858c7696e810a40c3fbfbfbc5e1/vendor/engines/saas/app/jobs/saas/app/board_index_job.rb) delegates to `GroupOwnerJob`, `IdentifyUserJob` and `TrackUserJob`
  - I assume this also runs conventionally, for `charges#create`.

#### Client

- [`shared/_analytics.html.erb`](https://github.com/huboard/huboard-web/blob/1bf5a79a80a47858c7696e810a40c3fbfbfbc5e1/app/views/shared/_analytics.html.erb):
  1. Loads Segment (if enabled)
  2. Fires `identify` if logged in
  3. Fires `page` (default parameters)
- [`layouts/ember.html.erb`](https://github.com/huboard/huboard-web/blob/82a924569ed9aa9ea2349d72ffc1745ab911798e/app/views/layouts/ember.html.erb#L20) renders `shared/analytics`
- [`layouts/application.html.erb`](https://github.com/huboard/huboard-web/blob/82a924569ed9aa9ea2349d72ffc1745ab911798e/app/views/layouts/application.html.erb#L69) renders `shared/analytics`
- [`layouts/marketing.html.erb`](https://github.com/huboard/huboard-web/blob/82a924569ed9aa9ea2349d72ffc1745ab911798e/app/views/layouts/marketing.html.erb#L65) renders `shared/analytics`
- [`board/index.html.erb`](https://github.com/huboard/huboard-web/blob/82a924569ed9aa9ea2349d72ffc1745ab911798e/app/views/board/index.html.erb#L53-L64) wires a `page` event into the Ember router
  - I don't know Ember well enough to say exactly how this is expected to work.
  - More generally, I thought this had been disabled on 2015-05-01 (as identified via GA page data)? Confused here.

#### Gaps

- Every view should render `shared/analytics` if doesn't use one of the layouts that does
  - Most important gap here is [`login.html.erb`](https://github.com/huboard/huboard-web/blob/82a924569ed9aa9ea2349d72ffc1745ab911798e/app/views/login/index.html.erb) - why doesn't this use a layout?
  - Views in [`errors/`](https://github.com/huboard/huboard-web/tree/82a924569ed9aa9ea2349d72ffc1745ab911798e/app/views/errors) would ideally include something in the `page` payload to identify what error was encountered - this may indicate usability issues
- Beyond tracking `/login`, we need to use `page` or `track` (I don't have strongly feeling either way) server-side to track the rest of the login flow. In particular, we need to track:
  - Initiating an OAuth request for access
  - Redirects back to us with granted access (not sure if we can tell new auths vs establishing existing auth on the current client)
- As far as I can tell, we're not actually tracking anything about the paywall funnel.
  - It seems best to me that we would treat the [Trial? prompt](https://github.com/huboard/huboard-web/blob/82a924569ed9aa9ea2349d72ffc1745ab911798e/vendor/engines/saas/app/views/saas/trials/show.html.erb) as a `page` view with an identifiable URL.
    - We also need to `track` when a trial is successfully started.
  - I've never seen the "your trial has expired" experience, but that also needs to be uniquely identifiable so we can include it in a funnel.
  - Similarly, we need to track all actions that can be taken from `/settings/profile` (Activate Trial, click Upgrade to prompt with Stripe, submit to Stripe)
- We do track `{owner}/{repo}/board/create`, but do not track if action is taken (by us or clicking out to GitHub Issues)
- Tracking all actions taken within the app will probably blow through our Segment budget, but it would be interesting to track first-per-session events on stuff like view issue, create issue, move issue, etc.

**Comment by rauhryan** [comment]
- [ ] we need to track the paywall
  - [ ] client-side tracking on login
  - [ ] server-side OAuth handshake tracking (what scope did they start in and what scope were they ultimately redirect to) 
  - [ ]

**Comment by dahlbyk** [comment]
> - I don't know Ember well enough to say exactly how this is expected to work.
> - More generally, I thought this had been disabled on 2015-05-01 (as identified via GA page data)? Confused here.

This does appear related to the ember-cli upgrade: https://github.com/huboard/huboard-web/commits/c52ca918bef882d4cbca23adc211158936e7cc07

**Comment by dahlbyk** [comment]
> `/{owner}/{repo}/board/trial` when email prompt is shown

@discorick observed that this is already firing as `/settings/{owner}/trial`, so I've aligned the expected page event for related account actions.

**Comment by discorick** [comment]
Was just working on the `settings.{owner}.expired` portion of this PR.

There are really two ways I can see about doing this:

#A:
Wait until a user hits `saas_unauthenticated` and check if the trial is expired, this logic would probably live in the `Saas::ErrorsController` and simply look for a trail expired key in couchDB, we would then call `Saas::AnaylticsPageJob` with the params. 

The downside is we will be potentially paging more than `settings.{owner}.expired`  events.  But it is the simplest implementation.

#B:
Handle via the incoming Stripe Webhook when the actual trial takes place. My approach would be to use a `WebhooksJob` that would conventionally queue up a `Stripe::CustomerUpdatedJob`, which in turn would handle all the logic we currently have in the `API::WebhooksController`, this would be the seam where I would also determine the expired trial and fire off the consequent `Saas::AnaylticsPageJob`

This is a more time intensive and complex approach, but I think it fits in the vision of eventually removing logic out `WebhooksController.stripe` endpoint altogether.

**Comment by dahlbyk** [comment]
B would then fire at the moment a trial expired, yes? I was more thinking that we want to track folks trying to _access_ a private repo that has expired. Leaning on Stripe for tracking actual trial expiration data is fine.

Related question: can/should we track account cancellations separately from trial expirations?

**Comment by discorick** [comment]
> can/should we track account cancellations separately from trial expirations?

Yes I think that should be seperate, stripe sends a `customer.subscription.deleted` for cancelations.

**Comment by dahlbyk** [comment]
> > I was more thinking that we want to track folks trying to access a private repo that has expired.
> 
> I am not sure how helpful that would be with Goal Tracking? (honest question)

A good question. GA Goal Tracking is 100% about knowing what's happening as users interact with the site, not so much about what's happening peripherally.

Why is this useful? Consider our main funnels to a paying customer:

1. "Subscribe to this plan" links from [`/pricing`](https://huboard.com/pricing)
2. "Upgrade Account" button from the "You'll need to upgrade your account to get those kinds of permissions." page.

The latter is precisely what I'm suggesting we need to track as `/settings/{owner}/expired` (or as `/settings/{owner}/cancelled` if we can tell the difference).

----------------------

Speaking of which, I noticed the actions in the issue description were changed to dot-delimited instead of slash-delimited. I'm 98% certain we want to track these as pages rather than events, and slashes seem much more natural (not to mention aligning with the existing `/settings/{owner}/trial`. Am I missing something?

**Comment by rauhryan** [comment]
Sorry, the dots were my suggestion. I was confused as to whether they were API end points or just event names. 

Tracking them as pages makes sense. 

Is there a better way to that those are a sort of 'virtual' page?

**Comment by discorick** [comment]
Ok, I see what you mean @dahlbyk, so we are looking a little bit of a matrix:

User hits `saas_unauthenticated`:
  - If user is admin:
   - We know the trial has expired at some point
   - We can probably determine if account is paid -> canceled 

- if user is collaborator 
  - We can determine if the trial has expired at some point
  - We can probably determine if account is paid -> canceled 

The difference between "determine" and "know" is my estimation of how many calls to couch or GitHub I will need to make in order to make the necessary checks to understand the current status of the Account. 

For instance the collaborator will require 2 couch queries, one for the current user, and another to lookup whether the Org they are attempting to reach already has an account, and if so, what is the status of that account. 

This is where not having a dedicated user/subscription model is hurting us a little bit, we have to chase down a trail of breadcrumbs to understand the state of accounts.

**Comment by discorick** [comment]
I think for simplicities sake I can start with just the admin/owner side of things, this will help us get a better understanding of things.

**Comment by dahlbyk** [comment]
> Is there a better way to that those are a sort of 'virtual' page?

@rauhryan I'm not sure I understand the question. Are you concerned about inflating traffic numbers? We already do this when offering a trial, all other cases will happen much less often (I expect).

----

@discorick Wouldn't we already need to have checked Couch for a repo owner subscription at the point we decide they are `saas_unauthorized`? Where does that code live?

**Comment by discorick** [comment]
`lib/use_case/private_repo.rb` is where the logic lives to determine whether a user saas_unauthorized.. I was trying to avoid adding to that mess (it's an area of the app that needs some TLC)

**Comment by dahlbyk** [comment]
So really it's a combination of `UseCase::PrivateRepo` and [`Saas.BeforeAction.check_account`](https://github.com/huboard/huboard-web/blob/82a924569ed9aa9ea2349d72ffc1745ab911798e/vendor/engines/saas/lib/saas/before_action.rb#L15-L30).

As currently modeled, I think `a_trial_available?` is on the right track in setting `params[:trial_available]`. Can we do something similar within `has_subscription?` to give us enough information with `:unauthorized` to identify (trial) `expired` or (account) `cancelled`? Is there an `:unauthorized` situation that _isn't_ `expired` or `cancelled` (since anyone else should be offered a trial)?

---

As an aside, [`/lib/hu_board/account_helpers.rb`](https://github.com/huboard/huboard-web/blob/82a924569ed9aa9ea2349d72ffc1745ab911798e/lib/hu_board/account_helpers.rb) and [`/vendor/engines/saas/app/helpers/saas/account_helpers.rb`](https://github.com/huboard/huboard-web/blob/82a924569ed9aa9ea2349d72ffc1745ab911798e/vendor/engines/saas/app/helpers/saas/account_helpers.rb) seem identical (latter added entirely in 5c30bd03ceab054c2f4a59d8ac45488e784ad305). Making collective mental note to reconcile that duplication.

**Comment by discorick** [comment]
I think it might be simplest to add `subscription_canceled?` & and `trial_expired?` methods, rather than trying to further complicate the current checks.

**Comment by dahlbyk** [comment]
Over [here](https://github.com/huboard/huboard-web/pull/207#issuecomment-187547297) I posted:

> On an unrelated note, your use of `trailing` here is interesting. I had proposed `trialed`, but I think `triailing` might be a better choice to differentiate from the account "states" of expired/canceled. The flow would be:
>
> * `trial` :point_right: `triailing` :point_right: `expired`
> * `upgrade` :point_right: `upgrading` :point_right: :`canceled`
> * `reactivate` :point_right: `reactivating` :point_right: `expired`
> 
> Our goals would be `trialing`, `upgrading` and `reactivating`.

I have tentatively aligned the Description here with what that might look like overall, and filled in proposals for the other `/settings/profile` actions. Thoughts?

**Comment by discorick** [comment]
The verbiage does seem better, it's going to require some minor changes to #207 and #208 . Should I go ahead and do that ?

**Comment by dahlbyk** [comment]
> The verbiage does seem better, it's going to require some minor changes to #207 and #208 . Should I go ahead and do that ?

If you're good with it, I'm good with it. Make it so!

---

FYI, I moved the #194 link up under bullet 3 rather than the `/login/(public|private)` task, which is still not complete.

**Comment by dahlbyk** [comment]
Now that #207 has shipped and we can set up the trial funnel, I'm thinking our priorities should be:

1. Upgrade funnel (`/settings/profile` actions)
2. Login funnel (`/login` to `/login/(public|private)` to GitHub and back)
3. Reactivation (https://github.com/huboard/huboard/issues/635)
4. Board creation

What do you think, @rauhryan?

**Comment by rauhryan** [comment]
Sounds good to me

**Comment by discorick** [comment]
I work on getting these out by end of week

**Comment by dahlbyk** [comment]
> `/settings/{owner}/upgrade` when Upgrade is clicked (popping Stripe)

Let's consider this one blocked by #158/#189/#209. We can always add a new step in the middle of the Goal Funnel.

**Comment by dahlbyk** [comment]
> `settings/{owner}/upgrade` when Upgrade is clicked (popping Stripe)

Now unblocked with merge of #209, if you want to knock that out at some point @discorick. Once that's done I think we can call this good.

**Comment by discorick** [comment]
Ok! I think we have satisfied the requirements of this issue. Can we close @rauhryan @dahlbyk ?

**Comment by dahlbyk** [comment]
Do we want to leave open until #253 ships and we can consider the goals in GA finalized (for now)?

**Comment by discorick** [comment]
Closing as #253 is shipped!
